### ISSUE TITLE
Hi I am getting an error Array component doesnt exist

### ISSUE THREAD

**Issue by fuhadabdulla** [Thomsr/sorting-animations#1]
I am trying to learn motion canvas and found your project in discord .

when i run your code there is error in this line of code that array component doesnt exist 

import { Array } from '../../components/ArrayComponent/Array';

can you please tell me what should i do

**Comment by Thomsr** [comment]
Have you also pulled the sub git module ArrayComponent ?

**Comment by fuhadabdulla** [comment]
Thank you so much . I didnt know i had to do that . it worked

**Comment by Thomsr** [comment]
np :)
